### ISSUE TITLE
generate minimal OWL file using ASCT+B terms as seed

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-validation-tools#111]
* Step 1:  Using all AS & CT terms from a single table, use SPARQL to query the *redundant* graph for all edges connecting terms in the seed, following the same limited set of properties we use for constructing AS_CT.owl.   Use SPARQL construct to generate a existential restrictions for all of these. (Not sure how well this will scale for a single SPARQL query)
* Step2:  Use Sparql to check whether properties use are transitive & add this with SPARQL construct  
* Step3: Use ROBOT reduce to save the results to an OWL output file
* Step4: Generate an graph to visualise

**Comment by dosumis** [comment]
Maybe try this on a single test file (e.g. Kidney) before running for all files.

**Comment by anitacaron** [comment]
![Kidney_all_edges_pairs](https://user-images.githubusercontent.com/2208124/143602087-0d628712-f32a-4377-93f7-954fe57443fa.png)

Does it look good?

**Comment by anitacaron** [comment]
When using og2dot, it removes everything about kidney term. I don't know why yet.

**Comment by dosumis** [comment]
Wow.  That was fast!

Looks good but:
  * I think it needs the kidney term to be usable.
  * Can you check for overlaps only if part_of not found (otherwise) all part_of edges get overlaps too.  If this is too much hassle for a first release, just drop overlaps.
  * Please drop develops_from

**Comment by anitacaron** [comment]
![Kidney_all_edges](https://user-images.githubusercontent.com/2208124/143607843-e83358bc-c18a-4cbb-8721-b44b586d405a.png)

I dropped the overlaps. I'll think of a way to have it only if part of not present.

**Comment by dosumis** [comment]
Some puzzles:

1. Are you using the old parser again?  I see some terms, like 'kidney interstitium' and 'kidney vasculature' that were missing previously due to issues with JSON.  (Not a criticism - just trying to keep up)
2. Some terms in the first graph are singletons but should be wired up, e.g.  
![image](https://user-images.githubusercontent.com/112839/143609688-fdbb7f53-49c1-4f46-bdf1-6c80ff12e61a.png)
should have a part_of relationship to 'kidney interstitum' - these terms are missing from graph 2
3. Some other edges missing, e.g. 'renal efferent arteriole' should be under 'kidney vasculature' and under 'renal corpuscle'

**Comment by anitacaron** [comment]
1. The table changed, it was "fixed". I'm running the logs again, btw.

**Comment by anitacaron** [comment]
![Kidney_all_edges](https://user-images.githubusercontent.com/2208124/144224292-bc4487cd-5b0a-4ac0-b9bb-9d0ab0bc93e2.png)

**Comment by dosumis** [comment]
Looks good.   Bit ,ore complicated than I expected. I'm wondering if there's still some redundancy in the graph.  Did you put it through a [robot reduce](http://robot.obolibrary.org/reduce) step?

**Comment by anitacaron** [comment]
Yes 
```
robot  reduce --reasoner ELK -i ../owl/Kidney_all_edges.owl -o ../owl/Kidney_edges_reduced.owl \
                 convert --format json -o Kidney_all_edges.json
 ```

**Comment by anitacaron** [comment]
![Kidney_all_edges](https://user-images.githubusercontent.com/2208124/144243064-e2eac46d-79d5-4621-ab30-2aaa5eb5540b.png)

**Comment by dosumis** [comment]
I think this is probably now good.  We should compare to the graph old graph in this PR 
https://github.com/anitacaron/souffle_test/diffs?base_sha=c2a6e17b34f1f181027b546a0a730e172d682527&bytes=4932&commentable=true&lines=108&pull_number=1&responsive=true&sha1=c2a6e17b34f1f181027b546a0a730e172d682527&sha2=494df7986a6419990d45bdfeb24dccdfca2108ae&start_entry=2&sticky=true&w=false&short_path=540fa48#diff-540fa480fbed2c76ac465f7af48f56bf80b0404740a60e76fb9b1eefffa7f776
 - should really be the same....  although maybe we should wait til the work on the Souffle pipeline has stabilised...

Also wondering how this scales.  Can we build these for all tables on GA or will we max out time/resources?

**Comment by anitacaron** [comment]
They aren't the same. 

I run `robot diff --left kidney-minimal.owl (this one) --right extended.owl (from souffle_test repo) --output diff`

Got these results: only counting the existential and subClassOf axioms
79 axioms in left ontology but not in right ontology 
15 axioms in right ontology but not in left ontology, including 8 class definition

If they should be the same, which process to obtain this should it choose? Maybe using relation-graph and downloading CL and UBERON is more efficient.

**Comment by anitacaron** [comment]
This was moved to the repository https://github.com/hubmapconsortium/ccf-rdf-writer
