### ISSUE TITLE
Add release notes

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-validation-tools#133]
Releases should include release notes that document version/date of tables tested against + versions Uberon & CL tested against. 

This may require some work with upstream resources:
 - Does CCF API supply version as date on sheets (or could we just use a datestamp for when test was run)
 - Can we get Ontology version metadata from UberGraph?

**Comment by anitacaron** [comment]
> Does CCF API supply version as date on sheets (or could we just use a datestamp for when test was run)

Besides the `data` key, the `parsed` key is the raw table structured as a list of lists, each list being a row in the table. In rows 8 and 9, there is information about the date and version number. It's easy to get this data.

> Can we get Ontology version metadata from UberGraph?

There isn't any result when searching for `owl:versionInfo`. Maybe this information is lost when merging all ontologies.

**Comment by bherr2** [comment]
Probably the best way to get version info for asct+b tables is with the now-externalized sheet configuration used by the asctb reporter: https://hubmapconsortium.github.io/ccf-asct-reporter/assets/sheet-config.json it includes all sheets and version info. You may even be able to use the config file to automate inclusion of new tables into the validation pipeline.

**Comment by bherr2** [comment]
Oh yeah, what @anitacaron said :-) but there still might be some utility in this other thing I linked to.

**Comment by anitacaron** [comment]
@bherr2 thank you for sharing this file. It'll be easier to generate the release notes from it.

**Comment by dosumis** [comment]
@balhoff - Is there any programmatic way to find what ontology versions are loaded into UberGraph?

**Comment by balhoff** [comment]
There isn't right now, and I agree it is a problem. There is a `robot merge` step in the build which loses the versions. I made an issue which I will prioritize: https://github.com/INCATools/ubergraph/issues/39

**Comment by dosumis** [comment]
https://api.triplydb.com/s/P-OrHuBFe
