### ISSUE TITLE
A proposed extension to CCF_AS_CT.owl

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-validation-tools#143]
STATUS: Draft.  Discussion required prior to implementation.

In cases where tables do not validate well, CCF_AS_CT.owl can have too few relationships to be useful.  Even in cases that do validate, some terms may float free from the graph, even if they are well connected in Uberon & CL. The proposal aims to take advantage of that connectedness.

Proposal:
For every orphan term (one with no existential restrictions), find all relationships by permitted relation types in the redundant graph to other terms the table.  Then use standard redundancy stripping (robot reduce) to remove any redundancy.   (I'm not sure of the best way to find orphan terms)

Note:  we need to ensure CCF.owl has fully axiomatised RO object properties for this to work - but we should make sure of that anyway.

**Comment by anitacaron** [comment]
I can take the orphan terms from the `class_{organ}_log` files and double-check in the validated cases.

Are there any restrictions on only checking CT-CT or AS-AS, or CT-AS?

**Comment by dosumis** [comment]
Initial spec is a bit sketchy

If we assume single inheritance - which I think holds for most or all the tables, then I think it would be safely to take the subject terms of all non-validating edges and add relations for all of those.  Also all this should be added to separate files and merged into the final product, as I think it would be very confusing for these term to show up in the graphs.  

### new Spec

Generate a new file for each table, containing the following:

* For each nonvalidating pair ASn+1-ASn, add all subclassof/part_of* relationships between ASn+1 and every other AS term in the table.
* For each nonvalidating pair AS-CL, add all part_of** relationships between CL and every AS term in the table.
* For each nonvalidating pair CL-CL, add all subclassof relationships between CL and every other CL term in the table

Merge all of the new files into the final release file, making sure there is a REDUCE step after the merge to strip redundancy.

\* We could consider connected_to here too, but need to test that redundancy stripping is sufficient. Leave out for now.
\** We could consider overlaps here too, but need to test that redundancy stripping is sufficient. Leave out for now.
\** We could consider develops_from here too. Leave out for now.

**Comment by dosumis** [comment]
Request for Josef - make additional merged artefacts for each organ/table.
