### ISSUE TITLE
Add `continuous_with` to the list of relationships to check

### ISSUE THREAD

**Issue by anitacaron** [hubmapconsortium/ccf-validation-tools#221]
Related to https://github.com/obophenotype/asct-b_validation/issues/66

**Comment by anitacaron** [comment]
This new relationship doesn't validate any case for the Eye table.

**Comment by aleixpuigb** [comment]
Can it be because the author is using the wrong label? 

UBERON:0006762 is `lens of camera-type eye`, `lens` is a synonym.

**Comment by anitacaron** [comment]
The validation is by the UBERON ID.

**Comment by anitacaron** [comment]
Do you have an example where it should validate?

**Comment by aleixpuigb** [comment]
`suspensory ligament of lens` (UBERON:0006762) is continuous with some `lens of camera-type lens` (UBERON:0006762)
![image](https://github.com/hubmapconsortium/ccf-validation-tools/assets/94959119/5c0e1d98-f73d-417f-ad69-f659bc79a3d8)
However is not validated:
![image](https://github.com/hubmapconsortium/ccf-validation-tools/assets/94959119/6bc3fc17-ed2d-4df2-9a9f-34f28e9cea55)

**Comment by anitacaron** [comment]
Fixed the issue, and now it validates. I'll run another release later.
