### ISSUE TITLE
Bogus present_in_taxon assertion on UBERON:8440041

### ISSUE THREAD

**Issue by gouttegd** [hubmapconsortium/ccf-validation-tools#293]
The file [UB_ASCTB_subset.owl](https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/owl/UB_ASCTB_subset.owl) asserts that [tuberal nucleus (sensu Rodentia)](http://purl.obolibrary.org/obo/UBERON_8440041) is [present in taxon](http://purl.obolibrary.org/obo/RO_0002175) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606).

As the label of the Uberon term implies, [tuberal nucleus (sensu Rodentia)](http://purl.obolibrary.org/obo/UBERON_8440041) is rodent-specific and is _not_ the same thing as the [lateral tuberal nucleus](http://purl.obolibrary.org/obo/UBERON_0000435) of primates.

**Comment by anitacaron** [comment]
It's in the Brain table, @emquardokus. Do we still have time to fix it?

**Comment by aleixpuigb** [comment]
In the Allen brain, line 111, AS5. We can propose to authors if [tuber cinereum](http://purl.obolibrary.org/obo/UBERON_0002620) is more appropriate since it is a related synonym of `tuberal region` (SME label) and it is part of the hypothalamus (AS4).

**Comment by emquardokus** [comment]
@anitacaron I've removed this and contacted Jeremy Miller for next revision.  I had not recommended this and in fact had written "no grouping term for regions within region" when looking through Uberon for hypothalamas to map the remaining regions of the brain that were in his table. I was specifically looking to see whether there were "exact synonyms" or conservative close synonyms which just had words mixed differently but not the absolute exact syntax as what was in his table. Anything questionable or with no exact or close to exact synonym, I did not recommend. This must have come from some sort of automated mapping he did.  I will discuss with him.  The suggestion by @aleixpuigb does look to be the correct match [tuber cinereum](http://purl.obolibrary.org/obo/UBERON_0002620) so I will mention to him.

**Comment by anitacaron** [comment]
Thank you, @emquardokus! I double-checked in the new release from today that the term [tuberal nucleus (sensu Rodentia)](http://purl.obolibrary.org/obo/UBERON_8440041) is not in the [subset file](https://github.com/hubmapconsortium/ccf-validation-tools/blob/ce17a735a5e1174a797301b64da8a109eca958fc/owl/UB_ASCTB_subset.owl).
