### ISSUE TITLE
All organs are duplicated in the dashboard

### ISSUE THREAD

**Issue by aleixpuigb** [hubmapconsortium/ccf-validation-tools#328]
All organs are duplicated, and therefore the sum of terms is doubled.
Large intestine is duplicated but with different numbers.

![image](https://github.com/hubmapconsortium/ccf-validation-tools/assets/94959119/969e0c85-3846-4d8f-8ee0-e1a3444877df)

**Comment by anitacaron** [comment]
This happens when two releases are run on the same day.
