### ISSUE TITLE
Different label: an instance not picked up in skin v1.3 or v1.4 DRAFT--check validation pipeline

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-validation-tools#329]
I was looking at Skin v1.4 draft https://docs.google.com/spreadsheets/d/1_xLnPyGyQy9fae7DrWkeyEN-iLTP8JQMxTL7HHkxG6o/edit?gid=269383687#gid=269383687 and found a mistake and looked at validation report because I wanted to report that I fixed it and the newest validation report ASCT+B Validation Reports for Skin (2024-06-19) https://hubmapconsortium.github.io/ccf-validation-tools/Skin/ was not going to the correct table---it was going to a v1.3 DOI'd table from December 2023.  

In the ASCT+B reporter, however, which uses what should be the same sheet-config.json you are using from us, the v1.4 DRAFT is correct, so not sure what's up there. https://hubmapconsortium.github.io/ccf-validation-tools/Skin/. It was incorrect in v1.3 too, but not showing in this report.  It should be under different labels.  

In v1.3 and original v1.4 draft one instance of  showed this "Perivascular smooth muscle cell	smooth muscle cell	CL:0000359" and the ontology label should be "vascular associated smooth muscle cell"  I'm surprised it wasn't picked up. (

@anitacaron ASCT+B Validation Reports for Skin (2024-06-19) is pointing to a DOI'd v1.3 skin table https://docs.google.com/spreadsheets/d/1q2tYQ_uNh5O_eLOMUZm64ncCUeJc8mrern3zkRX3Ppw/edit?gid=269383687#gid=269383687&range=56:56 rather than the v1.4_DRAFT table.

Skin_v1.4_DRAFT https://docs.google.com/spreadsheets/d/1_xLnPyGyQy9fae7DrWkeyEN-iLTP8JQMxTL7HHkxG6o/edit#gid=269383687

Found a Different label, but it did not show up in the validation report for either table.

FIXED: ROW 70 Perivascular smooth muscle cell smooth muscle cell CL:0000359 to match ontology ID vascular associated smooth muscle cell CL:0000359

Also FIXED: The term CL:0002521 has a different name/label in the source ontology in the following 1 row 56. The name/label in the ASCT+B table is subcutaneous fat cell and the one in the ontology is subcutaneous adipocyte. For reference, the given name/label by SMEs is Adipocyte. Please correct it in the columns AS/N/LABEL or CT/N/LABEL in the ASCT+B table.

**Comment by anitacaron** [comment]
> ASCT+B Validation Reports for Skin (2024-06-19) is pointing to a DOI'd v1.3 skin table rather than the v1.4_DRAFT table.

Yes, this is because I need to run the reports on the version that will be published. I just updated the config file here to run the report on the draft versions that are already available, and then I'll update later for the new draft versions. I'll re-run the release today with the drafts available.

**Comment by emquardokus** [comment]
> > ASCT+B Validation Reports for Skin (2024-06-19) is pointing to a DOI'd v1.3 skin table rather than the v1.4_DRAFT table.
> 
> Yes, this is because I need to run the reports on the version that will be published. I just updated the config file here to run the report on the draft versions that are already available, and then I'll update later for the new draft versions. I'll re-run the release today with the drafts available.

This doesn't make sense because the problem existed in BOTH and wasn't caught in either.

**Comment by anitacaron** [comment]
Sorry, I misunderstood that. The validation only checks the label for the first CL term, but two are in this table. The second one had a different label. I'll make sure to verify that the labels are the same for each case for the same term.
