### ISSUE TITLE
Missing 3D models in kidney terms

### ISSUE THREAD

**Issue by anitacaron** [hubmapconsortium/ccf-validation-tools#335]
I just checked this out and kidney 3D models are gone now from uberon. I checked small intestine, large intestine, pancreas, heart, lung, skin of body, spleen, prostate gland---all good.  I did not check all the organs we have models for, but this one stood out as it's one of our most popular. Can you check why this one is gone now?

_Originally posted by @emquardokus in https://github.com/obophenotype/uberon/issues/3315#issuecomment-2277815722_

**Comment by anitacaron** [comment]
@emquardokus I query the graph `<https://purl.humanatlas.io/ref-organ/kidney-female-left>` and the [kidney](http://purl.obolibrary.org/obo/UBERON_0002113) is not listed, however, we can see [left kidney](http://purl.obolibrary.org/obo/UBERON_0004538)

https://api.triplydb.com/s/8X1K0j5YJ

**Comment by emquardokus** [comment]
@bherr2 can you figure out why most of kidneys are missing?

**Comment by bherr2** [comment]
Not sure what you mean by missing. We don't have a 3d Spatial Entity of Kidney, we have it of Left Kidney.

**Comment by anitacaron** [comment]
I hope this is now clarified.
