### ISSUE TITLE
Add a build job for frozen tables

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-validation-tools#61]
Current reports/OWL build are for live tables. We should have one for the frozen tables to use for making official releases. 

CC @bherr2 @emquardokus to advise on how to reference these.  Use DOIs to resolve?

Related - in discussion with @bherr2 he suggested that we should be able to do full builds (without timeout) on GitHub Actions (although we should be careful of using GA resource budget for obophenotype (!).  He has some advice on avoiding timeouts.  We should track resources used though - might make more sense to switch to a Jenkins-based build using IU resources.

**Comment by balhoff** [comment]
I could provide a download of the database, so you could query it locally offline with blazegraph-runner. That's pretty straightforward to use; you don't have to start up a server. But if your queries are not timing out, that may not be necessary. Maybe there are ways to optimize some of your queries. When you have code like this:

```python
self.ask_uberon_po = """
PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050> 
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>
PREFIX FMA: <http://purl.obolibrary.org/obo/FMA_>
ASK
FROM <http://reasoner.renci.org/ontology>
FROM <http://reasoner.renci.org/redundant>
{ %s part_of: %s }"""
```

Does that mean you're submitting a separate query for every pair of `%s` terms of interest? I would do this instead if possible:

```sparql
PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050> 
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>
PREFIX FMA: <http://purl.obolibrary.org/obo/FMA_>
SELECT ?subject ?object
FROM <http://reasoner.renci.org/ontology>
FROM <http://reasoner.renci.org/redundant>
{ 
  VALUES (?subject ?object) {
    (<term1> <term2>)
    (<term1> <term3>)
    (<term2> <term3>)
    # etc.
  }
  ?subject part_of: ?object .
}
```

Fill in the VALUES table programmatically. Then the pairs you get back are the ones where the relation holds. If you are checking all the same pairs for different relations, this query could be expanded with another VALUES list of the relations, and it would check all combinations of relations and pairs.

> For multiple queries in series against the endpoint, should we be setting some spacing?

If you are querying serially, it's probably not necessary to space them out at the moment.
