### ISSUE TITLE
Add synonyms checker

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-validation-tools#7]
check user provided term name against label and synonyms

- [ ] write sparql query  Endpoint = https://stars-app.renci.org/uberongraph/sparql (you can practise queries of this endpoint though https://api.triplydb.com/s/hFwcvdil2)
- [ ] Add method to [uberongraph_tools](https://github.com/obophenotype/CCF_tools/blob/master/src/uberongraph_tools.py#L3)

**Comment by anitacaron** [comment]
This is not relevant anymore.
