### ISSUE TITLE
Import Bruce's CCF.owl

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-validation-tools#98]
URL = TBA

Or instructions on how to run API call => the tables we want.

@bherr2

**Comment by bherr2** [comment]
Here is an extra long URL that downloads all 11 v1.0 ASCT+B Tables as OWL (with relationships as Annotation Properties): 
[link](https://asctb-api.herokuapp.com/v2/csv?output=owl&expanded=true&subclasses=false&csvUrl=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D1379088218|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D1845311048|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D2133445058|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D1440276882|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D2137043090|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D512613979|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D1824552484|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D1158675184|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D984946629|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D1823527529|https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0%2Fexport%3Fformat%3Dcsv%26gid%3D361657182)

To limit to just some tables or other tables use this API:

  `https://asctb-api.herokuapp.com/v2/csv?output=owl&expanded=true&subclasses=false&csvUrl={csvUrls}`

Where csvUrls is a pipe-delimited set of URLs that resolve to CSV files for processing.

We use this form for Google Sheet URLS: `https://docs.google.com/spreadsheets/d/{sheetId}/export?format=csv&gid={gid}` where sheetId and gid come from the google sheet url. You'll want to escape the characters like we do [here](https://github.com/hubmapconsortium/hubmap-ontology/blob/master/src/generate_asctb_owl.py#L12-L16).

You can see how we process this for the [CCF-ASCTB.owl](https://ccf-ontology.hubmapconsortium.org/ccf-asctb.owl) (which uses ObjectProperties, but that can be changed by adding `subclasses=false` to the URL like above): <https://github.com/hubmapconsortium/hubmap-ontology/blob/master/src/generate_asctb_owl.py> This should also give you an idea of how you could format the Google Sheets links.
